### ISSUE TITLE
npm distube problem

### ISSUE THREAD

**Issue by Fluffyacid** [djpie123/Buttube#1]
D:\Codes\Ace\node_modules\buttube\src\quick-buttube.js:14
        this.distube = new DisTube(client, { searchSongs: false, emitNewSongOnly: true });
_____________________^

TypeError: DisTube is not a constructor
    at new quickbuttube (D:\Codes\Ace\node_modules\buttube\src\quick-buttube.js:14:24)
    at Object.<anonymous> (D:\Codes\Ace\index.js:37:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by djpie123** [comment]
Hello sir, I read your problem and I want to let you know that my package will not work with djs v13, I am trying my best to release the version compatible with djs v13 ASAP.
regards
pie
